services:
  acp:
    build: 
      context: acp 
      dockerfile: Dockerfile-dev
    ports:
      - 10124:10124
    volumes:
      - ./acp:/home/dans/acp 
    tty: true
    command: "poetry run python -m src.main"
  ras:
    build:
      context : ras
      dockerfile: Dockerfile-dev
      args:
        - VERSION=0.1.8.1
    volumes:
      - ./ras:/home/dans/repository-assistant-service
    ports:
      - 2810:2810
    tty: true
    command: "poetry run python -m src.main"
  transformer: 
    build: 
      context: transformer 
      dockerfile: Dockerfile-dev
      args:
        - VERSION=0.5.9
    ports:
      - 1745:1745
    tty: true
    volumes:
      - ./transformer:/home/dans/dans-transformer-service
    environment:
      - BASE_DIR=/home/dans/dans-transformer-service
    command: "poetry run python -m src.main"